# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-user
  template:
    metadata:
      labels:
        app: ecommerce-user
    spec:
      containers:
        - name: ecommerce-user
          image: 0901324101/ecommerce-user:1.0.0
          ports:
            - containerPort: 8080